### PR TITLE
Remove unnecessary reflection usage in android backend

### LINKED ISSUE #5785: New R8 obfuscator with android
I tried releasing my game on android with enabled minifying. It did work with proguard, but the new R8 obfuscator did not work. I used the default proguard config file. 
I tried this https://badlogicgames.com/forum/viewtopic.php?t=29056 solution but it didn't work

#### Reproduction steps/code
Set `minifyEnabled true` in android/build.gradle

#### Version of LibGDX and/or relevant dependencies
Android Gradle plugin 3.4.0 and higher, in my case 3.4.2

#### Stacktrace
```
Couldn't construct AndroidInput, this should never happen
```

#### Please select the affected platforms
- [x] Android
- [ ] iOS (robovm)
- [ ] iOS (MOE)
- [ ] HTML/GWT
- [ ] Windows
- [ ] Linux
- [ ] MacOS

### PR DESCRIPTION
**Pull request by SimonIT**
This fixes #5785 because the new R8 obfuscator removes AndroidInput classes which were instantiated with reflection.

### CODE REVIEW

**Comment by MobiDevelop** [comment]
Just to confirm, you're testing this running on API 9?

**Comment by SimonIT** [comment]
The problem is that I don't got any old device with api level 9. I tried using the emulator, but it doesn't start. I also tried an api level 10 emulator, but it also doesn't start. So I'm not sure how I can test it. All emulators until api level 14 are deprecated

**Comment by MobiDevelop** [comment]
We can't accept this until it has been tested on API 9, or we increase the minimum sdk version. We can't just assume it is safe.

File: backends/gdx-backend-android/src/com/badlogic/gdx/backends/android/AndroidApplication.java [hunk 1]
```diff
@@ -214,18 +192,14 @@ protected void createWakeLock (boolean use) {
...
 		View rootView = getWindow().getDecorView();
 
-		try {
-			Method m = View.class.getMethod("setSystemUiVisibility", int.class);
-			if (getVersion() <= 13) m.invoke(rootView, 0x0);
-			m.invoke(rootView, 0x1);
-		} catch (Exception e) {
-			log("AndroidApplication", "Can't hide status bar", e);
-		}
+		if (getVersion() <= 13) rootView.setSystemUiVisibility(0x0);
```
Comment (intrigus) [inline backends/gdx-backend-android/src/com/badlogic/gdx/backends/android/AndroidApplication.java]: Does anybody know why it is this way?
Isn't the uiVisibility always changed to 0x1 the line below?

**Comment by Anuken** [comment]
I just want to point out that [libGDX doesn't work on API 9 anyway](https://github.com/libgdx/libgdx/issues/5755), so the best solution would be to change the minimum API level to 14 (as discussed).

File: backends/gdx-backend-android/src/com/badlogic/gdx/backends/android/AndroidApplication.java (hunk 1 above)
Comment (obigu) [reply backends/gdx-backend-android/src/com/badlogic/gdx/backends/android/AndroidApplication.java]: No idea, I think many things could be cleaned up because the whole immersive mode / status bar code is a bit of a mess right now. Have a look at https://github.com/libgdx/libgdx/issues/3335 and https://github.com/libgdx/libgdx/pull/5329.

**Comment by noblemaster** [comment]
I think we agree to move the API level to 14. Let's do that with this pull request also.

**Comment by SimonIT** [comment]
Is there any other location to increase the minSdk? I can't find more

**Comment by noblemaster** [comment]
Thanks! I think you got all the minSDK locations. I merged it for better or worse. :)

This also addresses https://github.com/libgdx/libgdx/issues/5755

**Comment by SimonIT** [comment]
I think me can also remove some proguard rules
