### PR TITLE
Fix GLFW window creation with ANGLE and Ubuntu with Nvidia GPU Drivers

### LINKED ISSUE #6860: `GLEmulation.ANGLE_GLES20` not so much friendly with Ubuntu 22.04 and Nvidia drivers
#### Issue details
With new Ubuntu update Wayland has become the default display server and probably some issues with Nvidia proprietary drivers are now rising. This is what I've noticed using LWJGL3 backend and ANGLE extension:

- `GLEmulation.ANGLE_GLES20` with Wayland and trying to active the Nvidia card: simply no effect. The default Intel IGPU is used (bad performances)
- `GLEmulation.ANGLE_GLES20` with X11 and trying to active the Nvidia card: Crash happens related to LWJGL
```
[LWJGL] GLFW_PLATFORM_ERROR error
    Description : EGL: Failed to create window surface: Arguments are inconsistent
    Stacktrace  :
        org.lwjgl.glfw.GLFW.nglfwCreateWindow(GLFW.java:2024)
        org.lwjgl.glfw.GLFW.glfwCreateWindow(GLFW.java:2197)
        com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.createGlfwWindow(Lwjgl3Application.java:524)
        com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.createWindow(Lwjgl3Application.java:462)
        com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.createWindow(Lwjgl3Application.java:448)
        com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:162)
        games.rednblack.editor.Main.main(Main.java:50)
```

Everything works fine with any other configuration (GL20 both Nvidia and Intel, GL30 both Nvidia and Intel, ANGLE_GLES20 with Intel IGPU).
This issue looks like something related more to drivers (https://www.phoronix.com/scan.php?page=news_item&px=Ubuntu-22.04-NVIDIA-XOrg-Back) or LWJGL itself and so hard to fix on libGDX side, but I think it's good to point out in any case.

#### Version of libGDX and/or relevant dependencies
libGDX: 1.10.1-SNAPSHOT
GPU: nvidia-driver-510

#### Please select the affected platforms
- [ ] Android
- [ ] iOS
- [ ] HTML/GWT
- [ ] Windows
- [X] Linux
- [ ] macOS

### PR DESCRIPTION
**Pull request by fgnm**
This is just a propose for a workaround to fix #6860 , I didn't understand the real root cause of this issue, this only info I was able to find was in GLFW docs https://www.glfw.org/docs/3.3/window_guide.html#GLFW_CONTEXT_CREATION_API_hint they advice some special behaviors with some Linux systems and X11 which looks like linked to the problem.

Any comments or insights would be highly appreciated.

### CODE REVIEW

File: backends/gdx-backend-lwjgl3/src/com/badlogic/gdx/backends/lwjgl3/Lwjgl3Application.java [hunk 1]
```diff
@@ -519,9 +519,24 @@ static long createGlfwWindow (Lwjgl3ApplicationConfiguration config, long shared
 			GLFW.glfwWindowHint(GLFW.GLFW_REFRESH_RATE, config.fullscreenMode.refreshRate);
 			windowHandle = GLFW.glfwCreateWindow(config.fullscreenMode.width, config.fullscreenMode.height, config.title,
 				config.fullscreenMode.getMonitor(), sharedContextWindow);
+
+			// On Ubuntu >= 22.04 with Nvidia GPU drivers and X11 display server there's a bug with EGL Context API
```
Comment (Dgzt) [inline backends/gdx-backend-lwjgl3/src/com/badlogic/gdx/backends/lwjgl3/Lwjgl3Application.java:523]: I've experienced this behavior on Arch Linux, so I think this problem is distribution independent. I've tested this changes and it works, so I approve it.

**Review by Dgzt — APPROVED** [review]

**Review by Tom-Ski — APPROVED** [review]
