### PR TITLE
Hiero: If a font lacks 'x', fall back to Arial and place a note.

### LINKED ISSUE #6359: Hiero crashes on startup on Windows
Hiero crashes on startup with the following stacktrace on Windows (both running from IDE and a jar):

```
com.badlogic.gdx.utils.GdxRuntimeException: No x-height character found in font
	at com.badlogic.gdx.graphics.g2d.freetype.FreeTypeFontGenerator.generateData(FreeTypeFontGenerator.java:331)
	at com.badlogic.gdx.graphics.g2d.freetype.FreeTypeFontGenerator.generateFont(FreeTypeFontGenerator.java:161)
	at com.badlogic.gdx.graphics.g2d.freetype.FreeTypeFontGenerator.generateFont(FreeTypeFontGenerator.java:152)
	at com.badlogic.gdx.tools.hiero.unicodefont.UnicodeFont.setRenderType(UnicodeFont.java:647)
	at com.badlogic.gdx.tools.hiero.Hiero.updateFont(Hiero.java:315)
	at com.badlogic.gdx.tools.hiero.Hiero$1FontUpdateListener.actionPerformed(Hiero.java:456)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
	at javax.swing.AbstractButton.doClick(AbstractButton.java:356)
	at com.badlogic.gdx.tools.hiero.Hiero$17.actionPerformed(Hiero.java:681)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
	at javax.swing.AbstractButton.doClick(AbstractButton.java:356)
	at com.badlogic.gdx.tools.hiero.Hiero$Renderer.create(Hiero.java:1419)
	at com.badlogic.gdx.backends.lwjgl.LwjglCanvas.create(LwjglCanvas.java:216)
	at com.badlogic.gdx.backends.lwjgl.LwjglCanvas$1.addNotify(LwjglCanvas.java:106)
	at java.awt.Container.addImpl(Container.java:1124)
	at java.awt.Container.add(Container.java:419)
	at com.badlogic.gdx.tools.hiero.Hiero.<init>(Hiero.java:183)
	at com.badlogic.gdx.tools.hiero.Hiero$21.run(Hiero.java:1598)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Exception in thread "AWT-EventQueue-0" java.lang.RuntimeException: No OpenGL context found in the current thread.
	at org.lwjgl.opengl.GLContext.getCapabilities(GLContext.java:124)
	at org.lwjgl.opengl.GL11.glGenTextures(GL11.java:1403)
	at com.badlogic.gdx.backends.lwjgl.LwjglGL20.glGenTexture(LwjglGL20.java:348)
	at com.badlogic.gdx.graphics.Texture.<init>(Texture.java:142)
	at com.badlogic.gdx.graphics.g2d.PixmapPacker$Page$1.<init>(PixmapPacker.java:504)
	at com.badlogic.gdx.graphics.g2d.PixmapPacker$Page.updateTexture(PixmapPacker.java:504)
	at com.badlogic.gdx.graphics.g2d.PixmapPacker.updatePageTextures(PixmapPacker.java:410)
	at com.badlogic.gdx.graphics.g2d.PixmapPacker.updateTextureRegions(PixmapPacker.java:402)
	at com.badlogic.gdx.graphics.g2d.freetype.FreeTypeFontGenerator.generateData(FreeTypeFontGenerator.java:464)
	at com.badlogic.gdx.graphics.g2d.freetype.FreeTypeFontGenerator.generateFont(FreeTypeFontGenerator.java:161)
	at com.badlogic.gdx.graphics.g2d.freetype.FreeTypeFontGenerator.generateFont(FreeTypeFontGenerator.java:152)
	at com.badlogic.gdx.tools.hiero.unicodefont.UnicodeFont.setRenderType(UnicodeFont.java:647)
	at com.badlogic.gdx.tools.hiero.Hiero.updateFont(Hiero.java:315)
	at com.badlogic.gdx.tools.hiero.Hiero$3.valueChanged(Hiero.java:440)
	at javax.swing.JList.fireSelectionValueChanged(JList.java:1802)
	at javax.swing.JList$ListSelectionHandler.valueChanged(JList.java:1816)
	at javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:184)
	at javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:164)
	at javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:211)
	at javax.swing.DefaultListSelectionModel.changeSelection(DefaultListSelectionModel.java:405)
	at javax.swing.DefaultListSelectionModel.changeSelection(DefaultListSelectionModel.java:415)
	at javax.swing.DefaultListSelectionModel.setSelectionInterval(DefaultListSelectionModel.java:459)
	at javax.swing.JList.setSelectedIndex(JList.java:2216)
	at javax.swing.JList.setSelectedValue(JList.java:2366)
	at com.badlogic.gdx.tools.hiero.Hiero.<init>(Hiero.java:190)
	at com.badlogic.gdx.tools.hiero.Hiero$21.run(Hiero.java:1598)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

I've tested an old Hiero.jar I had locally and it doesn't crash so I guess it's realted to a recent change.

This seems to be related https://github.com/libgdx/libgdx/issues/6202

### PR DESCRIPTION
**Pull request by tommyettinger**
At least some of the font generators in Hiero require the 'x' character to be present in a font to use it, but Hiero also remembers the last-selected font for the next startup, and doesn't forget it if it's invalid. This PR makes Hiero forget the selection of the invalid font (removing its name from Preferences), sets the selected font to Arial (which should be available anywhere, since Hiero already fell back to it as a backup in one other place), and writes out a note in the sample text that says that Arial was selected and why (missing 'x'). The note can be easily removed just by pressing the ASCII, NeHe, or Extended buttons, but it lets the user know why Arial was selected instead of some emoji-only font or something. This fixes #6359 , as far as I can tell. It also means there isn't a large stack trace posted where most users can't see it, and the note in the sample text gives some indication of why the selection changed.

### CODE REVIEW

File: extensions/gdx-tools/src/com/badlogic/gdx/tools/hiero/Hiero.java [hunk 1]
```diff
@@ -436,7 +436,14 @@ private void initializeEvents () {
 			public void valueChanged (ListSelectionEvent evt) {
 				if (evt.getValueIsAdjusting()) return;
 				prefs.put("system.font", (String)fontList.getSelectedValue());
-				updateFont();
+				try {
+					updateFont();
+				} catch (GdxRuntimeException ex) {
+					prefs.remove("system.font");
+					fontList.setSelectedValue("Arial", true);
```
Comment (MrStahlfelge) [inline extensions/gdx-tools/src/com/badlogic/gdx/tools/hiero/Hiero.java:443]: I would prefer to select the first available value instead. Did you try if that works?

Comment (tommyettinger) [reply extensions/gdx-tools/src/com/badlogic/gdx/tools/hiero/Hiero.java:443]: The first available value isn't guaranteed to have the 'x' either, depending on what fonts the user has installed. Either this could loop until it finds a valid font (possibly never, but that shouldn't ever happen...), or it could use a font we know, or at least believe, is there already, and is valid.  Hiero already falls back to Arial in one case.

Comment (MrStahlfelge) [reply extensions/gdx-tools/src/com/badlogic/gdx/tools/hiero/Hiero.java:443]: You are right. What happens if you select such a font while using Hiero? It will also switch back to Arial. I am not sure if this is a good UX, maybe it is enough to just show the error to the user.

**Comment by obigu** [comment]
Thanks. I've tested and it's still failing in the same place. The issue is that the exception is not catched (it's a `RuntimeException.class`). Even when catching the exception correctly it fails. The selected font is not Arial but one called `Abster` (seems like it picks the first in alphabetical order). Some other day I can debug more if you don't know what the issue is.

File: extensions/gdx-tools/src/com/badlogic/gdx/tools/hiero/Hiero.java (hunk 1 above)
Comment (tommyettinger) [reply extensions/gdx-tools/src/com/badlogic/gdx/tools/hiero/Hiero.java:443]: I don't think it should permit such fonts to stay selected; they break at least the Freetype font generator, maybe also Java and Native. It wouldn't be able to show a sane glyph window, though the sample text could show a bunch of not-supported squares (but it wouldn't have a readable error message, which is another reason why it needs to switch to a font that supports at least ASCII).

**Comment by tommyettinger** [comment]
I can change the catch block to attempt to catch any Exception, or maybe any Throwable (which is less desirable I think). It's still possible the RuntimeException is caused by some other, separate problem, since it seems to be related to OpenGL context. If the GdxRuntimeException is caused by the missing 'x', this should resolve that, but if the RuntimeException is caused by a different thing, who knows...

**Comment by tommyettinger** [comment]
Hm, well I'm glad this is merged except that I don't know if it resolved @obigu 's bug (I don't think it did completely, but may have helped part-way?). The font that was causing problems is something weird; "Abster" is mainly distributed as an .otf file, which I don't think Hiero can read, but also lacks `x` in any format. I was fairly sure this PR fixed a main problem where choosing a font file by-hand, where that font lacks `x`, but I haven't been able to verify that it works when the initially-selected font lacks `x`. It might be a simple copy+paste of the check in the by-hand selection though.
