### PR TITLE
Fix #6464: TMX built-in tile property "type" is now supported.

### LINKED ISSUE #6464: TiledMap tile property "Type" doesn't get loaded
#### Issue details
The `Type` property on tiles gets skipped [during loading](https://github.com/libgdx/libgdx/blob/bc314368a18e0c916437f3dd7b4172714e6abf8b/gdx/src/com/badlogic/gdx/maps/tiled/BaseTmxMapLoader.java#L635) and therefore isn't available in libgdx.

image

```xml
<tileset firstgid="1" name="Test" tilewidth="256" tileheight="256" tilecount="4" columns="0">
  <tile id="0" type="AAAA"> 
    <image width="32" height="32" source="Start.bmp"/>
```

#### Reproduction steps/code
* Create a new Tilemap in Tiled
* Add a Tileset
* Assign a Type on one of the Tiles
* Load the map into libgdx
* Type isn't available

image

#### Version of LibGDX and/or relevant dependencies
1.9.14

#### Please select the affected platforms
- [x] Android
- [x] iOS
- [x] HTML/GWT
- [x] Windows
- [x] Linux
- [x] MacOS

### PR DESCRIPTION
**Pull request by lyze237**
Previous PR request: https://github.com/libgdx/libgdx/pull/6465

I've found some time and implemented it in the way @mgsx-dev wanted it.

This however turns the PR into a breaking change compared to previously where it wasn't the case.

image

### CODE REVIEW

File: gdx/src/com/badlogic/gdx/maps/tiled/tiles/StaticTiledMapTile.java [hunk 1]
```diff
@@ -123,4 +127,32 @@ public StaticTiledMapTile (StaticTiledMapTile copy) {
 		this.id = copy.id;
```
Comment (mgsx-dev) [inline gdx/src/com/badlogic/gdx/maps/tiled/tiles/StaticTiledMapTile.java:127]: new fields need to be copied here.

File: gdx/src/com/badlogic/gdx/maps/tiled/TiledMapTile.java [hunk 2]
```diff
@@ -63,4 +63,21 @@
 	/** @return collection of objects contained in the tile */
 	public MapObjects getObjects();
 
+	/** Sets he content of the property "terrain" */
+	public void setTerrain(String terrain);
+	/** @return the content of the property "terrain" */
```
Comment (mgsx-dev) [inline gdx/src/com/badlogic/gdx/maps/tiled/TiledMapTile.java:68]: formatting issue ?

File: gdx/src/com/badlogic/gdx/maps/tiled/BaseTmxMapLoader.java [hunk 3]
```diff
@@ -634,13 +634,14 @@ protected abstract void addStaticTiles (FileHandle tmxFile, ImageResolver imageR
...
-		if (terrain != null) {
-			tile.getProperties().put("terrain", terrain);
-		}
-		String probability = tileElement.getAttribute("probability", null);
-		if (probability != null) {
-			tile.getProperties().put("probability", probability);
-		}
+		tile.setTerrain(terrain);
+
+		float probability = tileElement.getFloatAttribute("probability", 1f);
```
Comment (mgsx-dev) [inline gdx/src/com/badlogic/gdx/maps/tiled/BaseTmxMapLoader.java:639]: apparently default is 0 in tiled spec, see https://doc.mapeditor.org/en/stable/reference/tmx-map-format/#tile
however it might be better to keep it as Float (default null) in order to keep the previous behavior.

File: CHANGES [hunk 4]
```diff
@@ -1,4 +1,5 @@
 [1.10.1]
+- [BREAKING CHANGE]: Removed TiledMapTile default properties (terrain, probability, type) from the properties array and added them as getter/setters to the tile classes.
```
Comment (mgsx-dev) [inline CHANGES:2]: maybe add a line (API addition) to say that builtin 'type' field is now supported?

**Review by mgsx-dev — CHANGES_REQUESTED** [review]

File: gdx/src/com/badlogic/gdx/maps/tiled/BaseTmxMapLoader.java (hunk 3 above)
Comment (lyze237) [reply gdx/src/com/badlogic/gdx/maps/tiled/BaseTmxMapLoader.java:639]: I've set it to 1 as it defaults to 1.000 in the tiled editor. I however could change it to 0 though.

image

Previous behavior was a string, should I change it back to that instead?

Comment (mgsx-dev) [reply gdx/src/com/badlogic/gdx/maps/tiled/BaseTmxMapLoader.java:639]: Indeed, it's maybe more safe to keep it as String. Maybe some user code use it as string and encode some stuff in it, who knows..

**Review by mgsx-dev — APPROVED** [review]
LGTM

**Comment by MobiDevelop** [comment]
For background, the TiledMapTile was never intended to specifically map to the Tiled (TMX) idea of a tile, so I don't really agree with these changes.

**Comment by tommyettinger** [comment]
Is this still compatible with Tide? Do we still need to be compatible with Tide, or other editors? I think the naming conventions across the tiled package are very misleading, but I'm used to that in libGDX by now ("No no, you want an int array, not an IntArray!"). It isn't at all clear that Tiled, in class names, doesn't refer to Tiled (TMX), but to a rectangular-grid tiling, until you've really delved into the barely-documented tiled package. I think the JavaDocs for TiledMapTile, which currently only has a `@brief` summary, could really use some attention from someone who actually knows what the intent behind TiledMapTile is, rather than the rest of us guessing at it.

As an aside, we've had lots of issues on the Discord and I believe also here on GitHub relating to newer features in the Tiled map format, such as infinite maps. If any PRs are going to be challenged by the lack of documentation in the tiled package, of intent or otherwise, then that documentation should be improved, or the challenges should be considered moot.

**Comment by MobiDevelop** [comment]
Ultimately, it's y'all's project now... I suppose. If you guys want to change things, I'm not going to block it. But just because you believe the name TiledMap specifically refers to the Tiled Editor doesn't make it so.

**Comment by mgsx-dev** [comment]
@MobiDevelop since we already merge "terrain" and "probability" properties into custom properties and then potentially override custom properties with same names, what's the best move? merge "type" property as well or introduce a kind of prefix for them?
I'm not fan of both solutions, i can't see an elegant solution right now, any suggestion?

**Comment by MobiDevelop** [comment]
I'd probably go the route that you add the 'built-in' values first, and if they chose to add a custom property with the same name have it override the built-in.

**Comment by lyze237** [comment]
soo the way how I did it in the first pr initially (ignoring the later change with /t)?

**Comment by MobiDevelop** [comment]
Looks like it, yeah.

**Review by mgsx-dev — APPROVED** [review]

**Comment by mgsx-dev** [comment]
side note: i was wrong, custom properties already override builtin ones. So this change doesn't break anything.

File: CHANGES [hunk 5]
```diff
@@ -3,6 +3,7 @@
 - API Addition: PointSpriteParticleBatch blending is now configurable.
 - TOOLS Features: Blending mode and sort mode can be changed in Flame particle 3D editor.
 - API Addition : Polygon have method setVertex (int index, float x, float y)
+- API Addition:
```
Comment (MobiDevelop) [inline CHANGES:6]: I guess this line is either not needed or should be completed.

**Review by MobiDevelop — APPROVED** [review]

File: CHANGES (hunk 5 above)
Comment (lyze237) [reply CHANGES]: No clue why it disappeared, most likely due to all the force push magic. :D
