### PR TITLE
fix libgdx/libgdx#5488 ScrollPane scrollTo

### LINKED ISSUE #5488: Issue with ScrollPane.scrollTo
#### Issue details
If a large amount of content is loaded inside a ScrollPane, and you wish to scroll to the end of the content, multiple calls to ScrollPane.layout() are required. (You can find other examples of this issue on the web.)

#### Reproduction steps/code
ScrollPane created with the following code:

Table tblOuter = new Table();
Table tblInner = new Table();
lblChat = new Label("", skin, "small");
lblChat.setWrap(true);

tblInner.add(lblChat).width(chatWidth - 40f).padLeft(5f).top();
tblInner.add(new Label("", skin, "small")).fillX().right();
tblInner.row();

pneChat = new ScrollBarPane(tblInner, skin, "default");
tblOuter.add(pneChat).width(chatWidth - 20f).height(controlHeight - 30f).expand().row();

Then, if after a large amount of text is loaded in lblChat, layout() has to be called twice prior to scrollTo working:

pneChat.layout();
pneChat.layout();
pneChat.scrollTo(0, 0, 0, 0);

#### Version of LibGDX and/or relevant dependencies
1.9.9

#### Please select the affected platforms
- [ ] Android
- [ ] iOS (robovm)
- [ ] iOS (MOE)
- [ ] HTML/GWT
- [X ] Windows
- [X ] Linux
- [ ] MacOS

### PR DESCRIPTION
**Pull request by mgsx-dev**
Calling ScrollPane scrollTo just after changing children size didn't work.

A another way (workaround) was to manually validate scrollPane before calling scrollTo but i think it's better to do it automatically in ScrollPane class. @NathanSweet What do you think?

It fixes #5488 and in some way #4561 as well : I'll comment on the latest issue.

### CODE REVIEW

File: tests/gdx-tests/src/com/badlogic/gdx/tests/ScrollPaneWithDynamicScrolling.java [hunk 1]
```diff
@@ -0,0 +1,97 @@
+/*******************************************************************************
+ * Copyright 2011 See AUTHORS file.
```
Comment (Lonami) [inline tests/gdx-tests/src/com/badlogic/gdx/tests/ScrollPaneWithDynamicScrolling.java]: Are you supposed to still use 2011 in new copyright notices?

**Comment by NathanSweet** [comment]
I think it makes sense to validate inside scrollTo. Thanks!
