### PR TITLE
Fix crash if there more than one app launched with ANGLE emulation

### LINKED ISSUE #6804: Can't Launch more than one application
#### Issue details
Can't launch more than one application with ANGLE emulation.
(Can't even launch with RenderDoc despite no application is running)

#### Reproduction steps/code
Launch the application with ANGLE GLES20 emulation, and then launch it again.

#### Version of libGDX and/or relevant dependencies
1.10.1-SNAPSHOT

#### Stacktrace
```java
Exception in thread "main" com.badlogic.gdx.utils.GdxRuntimeException: Couldn't load ANGLE.
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loadANGLE(Lwjgl3Application.java:102)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:137)
	at com.andedit.dungeon.lwjgl3.Lwjgl3Launcher.createApplication(Lwjgl3Launcher.java:17)
	at com.andedit.dungeon.lwjgl3.Lwjgl3Launcher.main(Lwjgl3Launcher.java:13)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loadANGLE(Lwjgl3Application.java:98)
	... 3 more
Caused by: com.badlogic.gdx.utils.GdxRuntimeException: Couldn't load ANGLE shared library windows64/libEGL.dll
	at com.badlogic.gdx.backends.lwjgl3.angle.ANGLELoader.extractFile(ANGLELoader.java:93)
	at com.badlogic.gdx.backends.lwjgl3.angle.ANGLELoader.load(ANGLELoader.java:193)
	... 8 more
Caused by: java.io.FileNotFoundException: C:\Users\Owner\AppData\Local\Temp\libgdxOwner\9b0d1e9db1460d7d\libEGL.dll (The process cannot access the file because it is being used by another process)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
	at com.badlogic.gdx.backends.lwjgl3.angle.ANGLELoader.extractFile(ANGLELoader.java:79)
	... 9 more
```

#### Please select the affected platforms
- [ ] Android
- [ ] iOS
- [ ] HTML/GWT
- [x] Windows
- [x] Linux
- [ ] macOS (Not sure about the mac but maybe affected)

### PR DESCRIPTION
**Pull request by AndEditor7**
By simply checking if the file exists. It should allow to run more than one app and launch the app with RenderDoc.

Note: This change is untested, and I don't how to test it.
Fixes #6804

### CODE REVIEW

**Comment by PokeMMO** [comment]
You could simplify this down to a File#exists check due to the crc32 being used as the directory name.

File: extensions/gdx-lwjgl3-angle/src/com/badlogic/gdx/backends/lwjgl3/angle/ANGLELoader.java [hunk 1]
```diff
@@ -75,6 +75,10 @@ private static File extractFile (String sourcePath, File outFile) {
 			OutputStream out = null;
 			InputStream in = null;
 
+			if (outFile.exists()) {
+				return outFile;
+			}
```
Comment (tommyettinger) [inline extensions/gdx-lwjgl3-angle/src/com/badlogic/gdx/backends/lwjgl3/angle/ANGLELoader.java:80]: There's not much to say here; this is a reasonable check to have. Because different, incompatible versions of native libraries should pretty much always have different checksums, this should never encounter any problem with two different versions getting loaded by different applications. Approved!

**Review by tommyettinger — APPROVED** [review]
It's a 2-3 line extra check; I don't think anything here is harmful or controversial. It looks like this will at least help the situation with multiple ANGLE apps running at once.

**Comment by crykn** [comment]
Just tested it on Windows and it works. SharedLibraryLoader [basically does the same](https://github.com/libgdx/gdx-jnigen/blob/master/gdx-jnigen-loader/src/main/java/com/badlogic/gdx/utils/SharedLibraryLoader.java#L255). In addition, it compares the CRC of the file as well, but whether that would make sense here, no idea.

@AndEditor7, if you want to test it yourself, just set up a [working source copy](https://libgdx.com/dev/from-source/) of libGDX and then start two different ANGLE apps (for example, Lwjgl3TestStarter has an ANGLE option).

**Comment by noblemaster** [comment]
I got the same error. Also, the fix looks fine with me.

**Review by noblemaster — APPROVED** [review]
