### PR TITLE
Fix Particle Editor Issues after recent commits, close #6816

### LINKED ISSUE #6816: 2D particle effect freezes when loading a file
Please ensure you have given all the following requested information in your report.

#### Issue details
When I tried importing or loading a 2d particle effect file application freezes with below error

#### Reproduction steps/code
launch latest particle effect jar,
load any particle effect file
application will freeze

#### Version of libGDX and/or relevant dependencies
1.10.0

#### Stacktrace
```java
Exception in thread "AWT-EventQueue-0" java.lang.IndexOutOfBoundsException: index can't be >= size: 1 >= 1
        at com.badlogic.gdx.utils.Array.get(Array.java:155)
        at com.badlogic.gdx.tools.particleeditor.ParticleEditor.getEmitter(ParticleEditor.java:208)
        at com.badlogic.gdx.tools.particleeditor.ParticleEditor.reloadRows(ParticleEditor.java:154)
        at com.badlogic.gdx.tools.particleeditor.EffectPanel.emitterSelected(EffectPanel.java:137)
        at com.badlogic.gdx.tools.particleeditor.EffectPanel$10.valueChanged(EffectPanel.java:368)
        at java.desktop/javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:224)
        at java.desktop/javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:204)
        at java.desktop/javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:251)
        at java.desktop/javax.swing.DefaultListSelectionModel.insertIndexInterval(DefaultListSelectionModel.java:675)
        at java.desktop/javax.swing.JTable.tableRowsInserted(JTable.java:4533)
        at java.desktop/javax.swing.JTable.tableChanged(JTable.java:4469)
        at java.desktop/javax.swing.table.AbstractTableModel.fireTableChanged(AbstractTableModel.java:302)
        at java.desktop/javax.swing.table.AbstractTableModel.fireTableRowsInserted(AbstractTableModel.java:237)
        at java.desktop/javax.swing.table.DefaultTableModel.insertRow(DefaultTableModel.java:383)
        at java.desktop/javax.swing.table.DefaultTableModel.addRow(DefaultTableModel.java:357)
        at java.desktop/javax.swing.table.DefaultTableModel.addRow(DefaultTableModel.java:368)
        at com.badlogic.gdx.tools.particleeditor.EffectPanel.openEffect(EffectPanel.java:170)
        at com.badlogic.gdx.tools.particleeditor.EffectPanel$5.actionPerformed(EffectPanel.java:315)
        at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
        at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2313)
        at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
        at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
        at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:279)
        at java.desktop/java.awt.Component.processMouseEvent(Component.java:6626)
        at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3389)
        at java.desktop/java.awt.Component.processEvent(Component.java:6391)
        at java.desktop/java.awt.Container.processEvent(Container.java:2266)
        at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5001)
        at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
        at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
        at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
        at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4575)
        at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
        at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
        at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2780)
        at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
        at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:746)
        at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:744)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:743)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Exception in thread "LWJGL Application" java.lang.IndexOutOfBoundsException: index can't be >= size: 1 >= 1
        at com.badlogic.gdx.utils.Array.get(Array.java:155)
        at com.badlogic.gdx.tools.particleeditor.ParticleEditor.getEmitter(ParticleEditor.java:208)
        at com.badlogic.gdx.tools.particleeditor.ParticleEditor$Renderer.render(ParticleEditor.java:526)
        at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:232)
        at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:127)
```

#### Please select the affected platforms
- [ ] Android
- [ ] iOS
- [ ] HTML/GWT
- [x] Windows
- [ ] Linux
- [ ] macOS

### PR DESCRIPTION
**Pull request by fgnm**
As point out in #6816 this commit #6678 has introduced some issues in Emitter reading and manipulating operations. The reason is that since in Swing libGDX rendering runs on a different thread of the UI in some cases `ParticleEffect` emitters list is not synced with what UI shows producing a bunch of out of bounds exception.
This should also fix move emitter up/down operations.

Thanks :)

### CODE REVIEW

File: extensions/gdx-tools/src/com/badlogic/gdx/tools/particleeditor/EffectPanel.java [hunk 1]
```diff
@@ -165,7 +166,7 @@ void openEffect (boolean mergeIntoCurrent) {
 			JOptionPane.showMessageDialog(editor, "Error opening effect.");
 			return;
 		}
-		for (ParticleEmitter emitter : editor.effect.getEmitters()) {
+		for (ParticleEmitter emitter : new Array.ArrayIterator<>(editor.effect.getEmitters())) {
```
Comment (tommyettinger) [inline extensions/gdx-tools/src/com/badlogic/gdx/tools/particleeditor/EffectPanel.java:169]: This looks like a major improvement if there's concurrent modification happening.

File: extensions/gdx-tools/src/com/badlogic/gdx/tools/particleeditor/ParticleEditor.java [hunk 2]
```diff
@@ -205,7 +205,11 @@ public void setVisible (String name, boolean visible) {
 	}
 
 	public ParticleEmitter getEmitter () {
-		return effect.getEmitters().get(effectPanel.editIndex);
+		Array<ParticleEmitter> emitters = effect.getEmitters();
+		if (effectPanel.editIndex < emitters.size) {
```
Comment (tommyettinger) [inline extensions/gdx-tools/src/com/badlogic/gdx/tools/particleeditor/ParticleEditor.java:209]: This isn't as bulletproof as it maybe could be, since editIndex can sometimes be -1. It's probably fine, though, since that would have thrown an exception before, too.

**Review by tommyettinger — APPROVED** [review]
Although I don't understand the changes to emitterTableModel, I have definitely noticed the problems mentioned in the PR description, albeit intermittently. This looks like it targets the right parts of the code that could be problems. I'm approving for now; I'll try to test fully soon.

File: extensions/gdx-tools/src/com/badlogic/gdx/tools/particleeditor/ParticleEditor.java (hunk 2 above)
Comment (fgnm) [reply extensions/gdx-tools/src/com/badlogic/gdx/tools/particleeditor/ParticleEditor.java:209]: In theory the if condition here should be always true because when `emitterTable.getSelectedRow()` returns `-1` the `editIndex` field didn't get updated anymore. I left the check anyway because maybe there could be cases I didn't catch and prevent possible freezes.

File: extensions/gdx-tools/src/com/badlogic/gdx/tools/particleeditor/EffectPanel.java (hunk 1 above)
Comment (fgnm) [reply extensions/gdx-tools/src/com/badlogic/gdx/tools/particleeditor/EffectPanel.java:169]: I got nested iterators error while trying to read some particle effects with multiple emitters.

Comment (tommyettinger) [reply extensions/gdx-tools/src/com/badlogic/gdx/tools/particleeditor/EffectPanel.java:169]: Then this seems like the thing to use to fix it!

File: extensions/gdx-tools/src/com/badlogic/gdx/tools/particleeditor/ParticleEditor.java (hunk 2 above)
Comment (tommyettinger) [reply extensions/gdx-tools/src/com/badlogic/gdx/tools/particleeditor/ParticleEditor.java:209]: Yeah, in any case it's more robust than before.

**Comment by obigu** [comment]
Thanks! Merging now.

When testing I've noticed a minor issue unrelated to this fixes (it occurs on snapshot version as well) that I'll leave here for reference. 

Sometimes and pretty randomly the input text boxes don't allow editing. 

A way to reproduce is in a pretty consistent manner:
1. Chose a text box such as Zoom Level value and focus cursor in it to edit.
2. Left click twice on the canvas where the effect is preview. You'll notice how on first click the input cursor moves to the Pixels per Meter value text box and the second click makes the input cursor disappear.
3. Click on the Zoom level value text box to edit it.
4. Try to input some number. From time to time it won't allow you and it is not possible to edit any other text box until you click on the canvas once. 
5. If it does work and you can edit the text box, go back to 1.
